name: nginx

on:
  workflow_call:
    inputs:
      build_main:
        description: "Build using liboqs and oqsprovider main branches"
        required: false
        default: false
        type: boolean
      release_tag:
        description: "Which docker tag to push to"
        required: false
        type: string
  workflow_dispatch:
    inputs:
      build_main:
        description: "Build using liboqs and oqsprovider main branches"
        required: false
        default: false
        type: boolean
      release_tag:
        description: "Which docker tag to push to"
        required: false
        type: string

env:
  build-args: |
    LIBOQS_TAG=main
    OQSPROVIDER_TAG=main
  push: ${{ github.repository == 'open-quantum-safe/oqs-demos' && github.ref == 'refs/heads/main' && github.event_name != 'pull_request'  && inputs.build_main != 'true' }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        if: env.push == 'true'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        uses: docker/build-push-action@v6
        with:
          load: true
          context: nginx
          build-args: |
            MAKE_DEFINES=-j4
            ${{ (inputs.build_main == 'true') && env.build-args || null }}
          tags: oqs-nginx

      - name: Scan Docker Image
        if: matrix.arch == 'x86_64' && env.push == 'true'
        uses: docker/scout-action@v1.16.1
        with:
          image: oqs-nginx
          command: cves,recommendations
          sarif-file: nginx-scan-results.sarif

      - name: Upload Scan Results
        if: matrix.arch == 'x86_64' && env.push == 'true'
        uses: actions/upload-artifact@v4.4.3
        with:
          name: nginx-scan-results
          path: nginx-scan-results.sarif

      - name: Build the curl Docker image (with generic liboqs)
        uses: docker/build-push-action@v6
        with:
          load: true
          context: curl
          build-args: |
            MAKE_DEFINES=-j4
            LIBOQS_BUILD_DEFINES="-DOQS_OPT_TARGET=generic"
            ${{ (inputs.build_main == 'true') && env.build-args || null }}
          tags: oqs-curl-generic

      - name: Test nginx with curl generic
        run: |
          docker network create nginx-test &&
          docker run --network nginx-test --detach --rm --name oqs-nginx oqs-nginx &&
          sleep 2 &&
          docker run --network nginx-test oqs-curl-generic curl -k https://oqs-nginx:4433

      - name: Push Docker image to registries
        if: env.push == 'true'
        uses: docker/build-push-action@v6
        with:
          push: true
          context: nginx
          build-args: |
            MAKE_DEFINES=-j4
            ${{ (inputs.build_main == 'true') && env.build-args || null }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/nginx:${{ inputs.release_tag || 'latest' }}-${{ matrix.arch }}
            openquantumsafe/nginx:${{ inputs.release_tag || 'latest' }}-${{ matrix.arch }}

  push:
    if: ${{ github.repository == 'open-quantum-safe/oqs-demos' && github.ref == 'refs/heads/main' && github.event_name != 'pull_request'  && inputs.build_main != 'true' }}
    needs: build
    uses: ./.github/workflows/push-manifest.yml
    secrets: inherit
    with:
      image_name: nginx
      release_tag: ${{ inputs.release_tag || 'latest' }}
